# docker-compose.yaml
services:
  redis: 
    image: redis
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
      REDIS_HOST: 'redis'
    ports:
      - '8000:8000'
    depends_on:
      - redis
    restart: "no"
